# Plugin supports
# tmux-prefix-highlight
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_fg $COLOR_PREFIX_HIGHLIGHT_FG
set -g @prefix_highlight_bg $COLOR_PREFIX_HIGHLIGHT_BG

# General
set -g status-interval 5
set -g status on
set -g status-right-length 50
set -g status-left-length 20 # rio

# Window status alignment
set -g status-justify left

# Colors
set -g status-bg $COLOR_STATUS_BG
set -g status-fg $COLOR_STATUS_FG
set -g status-attr none

# Pane border
set -g pane-border-fg $COLOR_PANE_BORDER_NORMAL_FG
set -g pane-active-border-fg $COLOR_PANE_BORDER_ACTIVE_FG
set -g display-panes-colour $COLOR_DISPLAY_PANE_NORMAL_FG
set -g display-panes-active-colour $COLOR_DISPLAY_PANE_ACTIVE_FG
set -gqw window-status-activity-attr none

# Clock mode
setw -g clock-mode-colour $COLOR_CLOCK_MODE

# Messages
set -g message-fg $COLOR_MESSAGE_FG
set -g message-bg $COLOR_MESSAGE_BG
set -g message-command-fg $COLOR_MESSAGE_COMMAND_FG
set -g message-command-bg $COLOR_MESSAGE_COMMAND_BG