# Plugin supports
prefix_highlight_fg="#{@prefix_highlight_fg}"
prefix_highlight_bg="#{@prefix_highlight_bg}"
set -g @prefix_highlight_output_prefix "#[fg=$COLOR_PREFIX_HIGHLIGHT_BG]#[bg=$COLOR_DARKER]#[nobold]#[noitalics]#[nounderscore]#[fg=$COLOR_PREFIX_HIGHLIGHT_FG]#[bg=$COLOR_PREFIX_HIGHLIGHT_BG] "
set -g @prefix_highlight_output_suffix " #[fg=$COLOR_DARKER]#[bg=$COLOR_PREFIX_HIGHLIGHT_BG]"
set -g @prefix_highlight_copy_mode_attr "fg=$COLOR_PREFIX_HIGHLIGHT_FG,bg=$COLOR_PREFIX_HIGHLIGHT_BG,bold"

# Status bar
hostname="#[fg=$COLOR_LIGHTER,bg=$COLOR_SECONDARY,bold] #U@#H "
session_number="#[fg=$COLOR_LIGHTER,bg=$COLOR_SECONDARY,bold] #S "
day="#[fg=white,bg=$COLOR_DARK]%Y-%m-%d"
time="#[fg=white,bg=$COLOR_DARK]%H:%M"

set -g status-left "$session_number"
set -g status-right "#{prefix_highlight} $day $time $hostname"

# Windows status
window_status_number=" #[fg=$COLOR_LIGHTER,bg=$COLOR_DARK]#I#{?window_flags,#F, }|"
window_status_name="#[fg=white,bg=$COLOR_DARK]#W "
window_status_number_active="#[fg=$COLOR_LIGHTER,bg=$COLOR_LIGHT] #I |"
window_status_name_active="#[fg=$COLOR_LIGHTER,bg=$COLOR_LIGHT]#W "
set -g window-status-format "$window_status_number $window_status_name"
set -g window-status-current-format "$window_status_number_active $window_status_name_active"
set -g window-status-separator ""

# unset variables
setenv -gru prefix_highlight_fg
setenv -gru prefix_highlight_bg

setenv -gru hostname
setenv -gru session_number
setenv -gru day
setenv -gru time

setenv -gru window_status_number
setenv -gru window_status_name
setenv -gru window_status_number_active
setenv -gru window_status_name_active